### POST 
POST http://localhost:3000/servicos
Content-Type: application/json

{
    "tipo": "Teste",
    "preco": 30.00
}

### GET
GET http://localhost:3000/servicos

### GET
GET http://localhost:3000/servicos/619

### GET
GET http://localhost:3000/servicos/Corte

### PATCH
PATCH http://localhost:3000/servicos/619
Content-Type: application/json

{
    "tipo": "",
    "preco": 35
}

### DELETE
DELETE http://localhost:3000/servicos/619