### POST 
POST http://localhost:3000/servicos
Content-Type: application/json

{
    "tipo": "Teste de logica",
    "preco": 30.00
}

### GET
GET http://localhost:3000/servicos

### GET
GET http://localhost:3000/servicos/8575

### GET
GET http://localhost:3000/servicos/Corte

### PATCH
PATCH http://localhost:3000/servicos/8548
Content-Type: application/json

{
    "tipo": "Teste 1"
}

### DELETE
DELETE http://localhost:3000/servicos/8548