### POST 
POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "nome": "teste",
    "sobrenome": "",
    "email": "teste@gmail.com",
    "senha": "teste",
    "tipoCargo": "Cliente"
}

### GET
GET http://localhost:3000/usuarios

### GET
GET http://localhost:3000/usuarios/teste

### PATCH
PATCH http://localhost:3000/usuarios/ff3addde-6314-46ca-8228-a59bf7b6a16a
Content-Type: application/json

{
    "nome": "",
    "sobrenome": "testeteste",
    "email": "teste@gmail.com",
    "senha": "teste",
    "tipoCargo": "Profissional"
}

### DELETE
DELETE http://localhost:3000/usuarios/6de6148e-3135-45bc-b48d-474c78db57cb